name: CD

on:
  workflow_dispatch

jobs:
  deployment:
    runs-on: self-hosted
    environment: Deployment

    steps:
      - uses: actions/checkout@v4

      - name: Create .env file from secrets
        run: echo "${{secrets.DOT_ENV }}" > .env

      - name: Start up docker 
        run: docker-compose up -d --build
